development:
  host: "localhost"
  adapter: "postgresql"
  encoding: utf-8
  pool: 25
  database: "comphair"
testing:
  host: "localhost"
  adapter: "postgresql"
  encoding: utf-8
  pool: 25
  database: "comphair-test"
