development:
  host: "localhost"
  adapter: "postgresql"
  encoding: utf-8
  pool: 25
  database: "salon"
testing:
  host: "localhost"
  adapter: "postgresql"
  encoding: utf-8
  pool: 25
  database: "salon-test"
